import { ResponseCode, TransactionStatus, TransactionType } from "../src";

export function consoleJson(input:unknown) {
	if (input !== undefined) {
		console.log(JSON.stringify(input, null, 2));
	}
}

export async function sleep(seconds:number) {
	await new Promise(r => setTimeout(r, seconds * 1000));
}

export function generateUniqueMerchantReferenceId() {
	return (new Date()).getTime().toString();
}

export const EmptyObjectBuilder = {
	"captureResponse": () => ({
		response: {
			avsCode: null,
			avsMessage: null,
			cvvCode: null,
			cvvMessage: null,
			errorCode: null,
			errorDetail: null,
		},
		paymentMethod: {
			paymentMethodId: expect.any(String),
			creditCardNumber: null,
			expiryMonth: null,
			expiryYear: null,
			cvv: null,
			firstName: null,
			lastName: null,
			fullName: null,
			customerId: null,
			address1: null,
			address2: null,
			postalCode: null,
			city: null,
			state: null,
			country: null,
			email: null,
			phoneNumber: null,
			paymentMethodType: null,
			fingerprint: null,
			lastFourDigits: null,
			firstSixDigits: null,
			cardType: null,
			dateCreated: expect.any(Date),
			storageState: null,
		},
		transactionId: expect.any(String),
		transactionDate: expect.any(Date),
		transactionStatus: expect.any(Number),
		message: expect.any(String),
		responseCode: expect.any(String),
		transactionType: expect.any(String),
		merchantTransactionId: expect.any(String),
		customerId: expect.any(String),
		currencyCode: "USD",
		amount: 1000,
		gatewayToken: expect.any(String),
		gatewayType: expect.any(String),
		gatewayTransactionId: null,
		merchantAccountReferenceId: null,
		assignedGatewayToken: expect.any(String),
		orderId: expect.any(String),
		retryDate: null,
		retryCount: 0,
		dateFirstAttempt: expect.any(Date),
		description: null,
		productSku: null,
		subscriptionId: null,
		customerIp: null,
		shippingAddress: {
			address1: null,
			address2: null,
			postalCode: null,
			city: null,
			state: null,
			country: null,
		},
		referenceData: expect.any(String),
		disableCustomerRecovery: false,
		customVariable1: null,
		customVariable2: null,
		customVariable3: null,
		customVariable4: null,
		customVariable5: null,
	}),

	"voidResponse": () => ({
		response: {
			avsCode: null,
			avsMessage: null,
			cvvCode: null,
			cvvMessage: null,
			errorCode: null,
			errorDetail: null,
		},
		paymentMethod: {
			paymentMethodId: expect.any(String),
			creditCardNumber: null,
			expiryMonth: null,
			expiryYear: null,
			cvv: null,
			firstName: null,
			lastName: null,
			fullName: null,
			customerId: expect.any(String),
			address1: null,
			address2: null,
			postalCode: null,
			city: null,
			state: null,
			country: null,
			email: null,
			phoneNumber: null,
			paymentMethodType: expect.any(String),
			fingerprint: null,
			lastFourDigits: expect.any(String),
			firstSixDigits: expect.any(String),
			cardType: null,
			dateCreated: expect.any(Date),
			storageState: expect.any(String),
		},
		transactionId: expect.any(String),
		transactionDate: expect.any(Date),
		transactionStatus: expect.any(String),
		message: expect.any(String),
		responseCode: expect.any(String),
		transactionType: TransactionType.Void,
		merchantTransactionId: expect.any(String),
		customerId: expect.any(String),
		currencyCode: expect.any(String),
		amount: expect.any(Number),
		gatewayToken: null,
		gatewayType: expect.any(String),
		gatewayTransactionId: expect.any(String),
		merchantAccountReferenceId: null,
		assignedGatewayToken: expect.any(String),
		orderId: expect.any(String),
		retryDate: null,
		retryCount: expect.any(Number),
		dateFirstAttempt: expect.any(Date),
		description: null,
		customerIp: null,
		shippingAddress: {
			address1: null,
			address2: null,
			postalCode: null,
			city: null,
			state: null,
			country: null,
		},
		referenceData: expect.any(String),
		disableCustomerRecovery: false,
		customVariable1: null,
		customVariable2: null,
		customVariable3: null,
		customVariable4: null,
		customVariable5: null,

		productSku: null,
		subscriptionId: null,
	}),
};
